print("Hello, Word!")
print("Daniiar")
print("Aktan")
print("Aman")
print("Sultanmurat")
print("Umar")
print("Atai")
print("Janybek")
print("Dilbara")
print("Belek")
print("Maruf")
print("Seyto")
print("Aijan")
